language: cpp

compiler:
  - clang

language: c++

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev
  - if [ "$CC"  == "gcc"     ]; then export CC=gcc; fi
  - if [ "$CXX" == "g++"     ]; then export CXX=g++; fi
  - if [ "$CC"  == "clang"   ]; then export CC=clang; fi
  - if [ "$CXX" == "clang++" ]; then export CXX=clang++; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - $CXX --version
  - make
  - make test

notifications:
  email: false
