language: cpp

compiler:
  - clang
  - gcc

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.6
            - g++-5
            - gcc-5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - $CXX --version
  - make
  - make test

notifications:
  email: false
